services:
  app:
    image: nextjs-with-docker
    build:
      context: .
      dockerfile: ./build/development.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm run dev
